fix(): posts from channels detected as bots
vas3k/vas3k.club pull request #1076
Opened 2023-03-30 10:09 UTC by zyuhel

Possibly fixes #937

2023-03-30 10:11 UTC, igoose1 requested changes

2023-03-30 10:13 UTC, igoose1 commented on bot/handlers/whois.py
> +        if (hasattr(original_message, 'sender_chat') and original_message.sender_chat):
ну и все условие можно заменить на `if getattr(original_mesage, 'sender_chat', None)` :-)

2023-03-30 10:26 UTC, zyuhel commented on bot/handlers/whois.py
> +        if (hasattr(original_message, 'sender_chat') and original_message.sender_chat):
сорри, привычка писать всюду скобки :)

2023-06-27 11:33 UTC, skywinder commented
@zyuhel привет, решил обновить статусы старых PR.
спасибо за фикс, да выглядит как валидный фикс. 
ты его протестировал, это рабочее решение? 

правда еще не обсуждали с Васей, нужно ли это вообще фиксить. обсудим

2023-06-27 11:35 UTC, zyuhel commented
@skywinder нет, тупо по доке делал, непонятно пока как эту штуку нормально тестировать :(

2023-08-14 12:08 UTC, igoose1 approved these changes

2023-10-25 09:17 UTC, vas3k approved these changes

2023-10-25 09:22 UTC, merged