fix(): enable go to second level comments in battles
vas3k/vas3k.club pull request #1079
Opened 2023-04-03 19:27 UTC by zyuhel

#1070  In battles second level comments in fact are third levels, and go to new message skips them.

2023-04-03 19:36 UTC, vas3k requested changes
Ну нет. Править бизнес логику там, где просто не хватает доп разметки — это как добавлять машине пятое колесо, потому что кто-то не осилил параллельную парковку

2023-04-03 19:59 UTC, zyuhel commented
Тут момент в том что в battle'ах в принципе другая верстка, за счет того что у нас первый уровень комментов это не то чтобы комменты, это мнения, за ту или иную сторону, могу добавить заодно какой нибудь класс к самим батлам чтобы можно было только для них это сделать.

2023-04-03 20:00 UTC, vas3k commented
Там другая верстка просто потому что на нее забили болт. Добавить класс к верстке балтов — вот это правильный путь, да

2023-04-06 14:52 UTC, vas3k approved these changes

2023-04-06 14:53 UTC, merged