fix: add rfc3339 support to feed.json (and content_text visibility fix)
vas3k/vas3k.club pull request #1119
Opened 2023-06-29 10:34 UTC by vlle

Пофиксил ишшью, добавил тесты. Проверил валидатор через локальный сервер — вроде все ок. 

<img width="1183" alt="Снимок экрана 2023-06-29 в 13 33 54" src="https://github.com/vas3k/vas3k.club/assets/91570054/2826d261-562b-4a72-903c-511ae5e02c64">

2023-06-29 11:43 UTC, igoose1 requested changes

2023-06-29 11:43 UTC, igoose1 commented on posts/models/post.py
> +            "date_published": self.published_at.isoformat("T") + "Z",
А может так?

```suggestion
            "date_published": self.published_at.astimezone().isoformat("T"),
```

2023-06-29 11:43 UTC, igoose1 commented on posts/tests/test_api.py
> +        self.assertEqual(converted_post["date_published"], self.expected_time_fmt)
А дату тогда так можно проверять:

```suggestion
        self.assertIsNotNone(
            datetime.strptime(converted_post["date_published"],  '%Y-%m-%dT%H:%M:%S%z').tzinfo,
        )
```

2023-06-29 11:44 UTC, igoose1 commented
Свяжи, пожалуйста, с issue: добавь в описание PR строчку "`Closes #1110`". Тогда при закрытии PR, закроется issue.

2023-06-29 13:01 UTC, vlle commented on posts/models/post.py
> +            "date_published": self.published_at.isoformat("T") + "Z",
так лучше, да!

2023-06-29 13:25 UTC, igoose1 approved these changes

2023-06-29 13:26 UTC, igoose1 commented
Спасибо! Полезный Pull Request.

2023-06-30 07:59 UTC, igoose1 commented
Снижаю когнитивную нагрузку мейнтенейру:

1. PR фиксит реальный баг,

2. В нем есть тесты, новый фид проверен отдельным сервисом-валидатором.

Он меняет результат content_text: там теперь может быть "Контент для авторизованных пользователей, увы!" и не может быть null. Это правильно: теперь фид валиден.

@vas3k, можно мержить. Не ебанет. Ответственность беру на себя.

2023-06-30 09:06 UTC, vas3k commented on posts/models/post.py
> +            "content_text": self.text if self.is_public or including_private else "Контент для авторизованных пользователей, увы!",
```suggestion
            "content_text": self.text if self.is_public or including_private else "🔒",
```

2023-06-30 09:07 UTC, vas3k commented on posts/models/post.py
> +            "content_text": self.text if self.is_public or including_private else "Контент для авторизованных пользователей, увы!",
Не нравится хардкод аж целой строки в коде, предлагаю заменить на эмодзи

2023-06-30 09:24 UTC, vas3k approved these changes

2023-06-30 09:32 UTC, merged