Command "skip" for the bot
vas3k/vas3k.club pull request #1122
Opened 2023-07-01 08:38 UTC by shkaff

Created a skip command to skip unwanted replies from the chat to the Club.

Old behavior: When a user responds to a post in the chat (posted by the bot), this also adds a comment to the post on the website (if the length is sufficient).

New behavior: if the comment contains "/skip", "#skip" or "#ignore" it remains in the chat and is not posted to the website.

2023-07-01 08:39 UTC, igoose1 requested changes

2023-07-01 08:39 UTC, igoose1 commented on bot/handlers/comments.py
> +    for skip_word in ("/skip","#skip","#ignore"):
```suggestion
    for skip_word in ("/skip", "#skip", "#ignore"):
```

2023-07-01 08:41 UTC, igoose1 commented on bot/main.py
> +        "Добавь '/skip','#skip' или '#ignore', чтобы реплай не запостился в Клуб.\n\n"
```suggestion
        "Добавь /skip, #skip или #ignore, чтобы реплай не запостился в Клуб.\n\n"
```

2023-07-01 09:00 UTC, shkaff commented on bot/handlers/comments.py
> +    for skip_word in ("/skip","#skip","#ignore"):
Ага, хорошая мысль, спасибо!

2023-07-01 09:33 UTC, igoose1 commented on bot/handlers/comments.py
> +    for skip_word in ("/skip","#skip","#ignore"):
Если хорошая, apply suggestion!

2023-07-01 09:49 UTC, shkaff commented on bot/handlers/comments.py
> +    for skip_word in ("/skip","#skip","#ignore"):
[Так уже](https://github.com/vas3k/vas3k.club/pull/1122/commits/2f956138284dd9cddc697c9f12fc846a77d14ee0):)

2023-07-01 09:54 UTC, cra commented on bot/handlers/comments.py
> +        if skip_word in text:
[nitpick - можно игнорировать если лень] можно сделать так чтобы вложенности было меньше
```python
if any(skip_word in text for skip_word in ('/skip', '#skip', '#ignore')):
    return None
 ```

2023-07-01 09:59 UTC, igoose1 commented on bot/handlers/comments.py
> +    for skip_word in ("/skip","#skip","#ignore"):
Нет, шкаф, это не тот suggestion, их два было :-)  Эта строчка жо сих пор без пробелов.

2023-07-01 10:03 UTC, igoose1 commented on bot/handlers/comments.py
> +        if skip_word in text:
В Python всегда можно написать что-то в одну строчку, но надо следить, чтобы оставалось читаемо. Здесь читаемость будет спорной :-)

2023-07-01 10:19 UTC, shkaff commented on bot/handlers/comments.py
> +    for skip_word in ("/skip","#skip","#ignore"):
Я что-то не понимаю. Здесь есть все нужные пробелы.

<img width="818" alt="image" src="https://github.com/vas3k/vas3k.club/assets/2661956/8a9dc3fc-0692-4273-9678-c9fb3c4d6704">

2023-07-01 10:32 UTC, igoose1 commented on bot/handlers/comments.py
> +    for skip_word in ("/skip","#skip","#ignore"):
Да, на твоем скриншоте — все нужные. Я о строке в bot/handlers/comments.py. Посмотри, под каким куском кода мы общаемся.

2023-08-01 13:40 UTC, vas3k approved these changes

2023-08-01 13:40 UTC, merged