Add ask bot
vas3k/vas3k.club pull request #1172
Opened 2024-01-29 23:06 UTC by Maxuz

Телеграм бот для справочной клуба

2024-01-30 03:23 UTC, ozeranskii commented on askbot/models.py
> +    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL) # TODO discuss on_delete action
думаю что SET_NULL не очень подходит по причине того, что при удалении user останутся "подвисшие" вопросы без идентификатора. В данном случае лучше, как мне кажется, либо PROTECT/RESTRICT либо CASCADE (но это. создает не очевидное удаление). Так же релевантно что user это not nullable столбец.

2024-01-30 03:25 UTC, ozeranskii commented on askbot/room.py
> +    return list(Room.objects.filter(is_visible=True, chat_id__isnull=False).all())
возможно стоит добавить сортировку?

2024-01-30 03:26 UTC, ozeranskii commented on askbot/handlers/question.py
> +REQUEST_FOR_INPUT, INPUT_RESPONSE, FINISH_REVIEW = range(3)
_nit_
это тоже может быть Enum.

2024-01-31 00:13 UTC, Maxuz commented on askbot/models.py
> +    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL) # TODO discuss on_delete action
Тоже так считал, а потом подумал, что ценность в самом вопросе и в ответах, а кто его задал, уже не так уж и важно. Но, не настаиваю, могу сделать поставить любую политику.

2024-01-31 00:17 UTC, Maxuz commented on askbot/room.py
> +    return list(Room.objects.filter(is_visible=True, chat_id__isnull=False).all())
Могу ошибаться но у Room уже есть предустановленная сортировка по полю `index`:
```python
    class Meta:
        db_table = "rooms"
        ordering = ["index"]
```
Этого будет достаточно?

2024-01-31 01:17 UTC, Maxuz commented on askbot/handlers/question.py
> +REQUEST_FOR_INPUT, INPUT_RESPONSE, FINISH_REVIEW = range(3)
Done!

2024-02-05 15:00 UTC, ozeranskii commented on askbot/models.py
> +    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL) # TODO discuss on_delete action
мне кажется что ценность исторических данных есть, например, для дальнейшего анализа или может обучение ML. Предлагаю реализовать soft delete подход как пользователей, так и ответов и вопросов.

2024-02-05 15:01 UTC, ozeranskii commented on askbot/room.py
> +    return list(Room.objects.filter(is_visible=True, chat_id__isnull=False).all())
не увидел, но я придерживаюсь более явного поведения. То есть сортировка на уровне запроса более явно описывает результат.

2024-02-05 15:04 UTC, ozeranskii commented on askbot/handlers/question.py
> +class State(Enum):
для `Enum` без использования `auto()` лучше еще использовать декоратор `@unique`. Это защитит от наличия дубликатов в значениях.

2024-02-05 15:08 UTC, ozeranskii commented on askbot/handlers/question.py
> +            f"🔗 <a href=\"{link}\">Ссылка на твой вопрос, там же ты сможешь найти ответы</a>",
в PR часто встречается генерация HTML link, предлагаю шаблонизировать это дело.
```python
hyperlink_format = '<a href="{href}">{text}</a>'
...
hyperlink_format.format(href='https://example.com', text='text')

# or

hyperlink_format = '<a href="{href}">{text}</a>'.format
...
hyperlink_format(href='https://example.com', text='text')
```

2024-02-05 23:09 UTC, Maxuz commented on askbot/models.py
> +    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL) # TODO discuss on_delete action
Предлагаю дождаться @vas3k , т.к. реализация очень сильно зависит от того как будет использоваться в дальнейшем. Сейчас мы пытаемся **придумать** возможные варианты, на имплементацию которых нужно будет тратить время, и возможно оно вообще не нужно.

2024-02-05 23:29 UTC, Maxuz commented on askbot/handlers/question.py
> +            f"🔗 <a href=\"{link}\">Ссылка на твой вопрос, там же ты сможешь найти ответы</a>",
Done

2024-02-05 23:29 UTC, Maxuz commented on askbot/handlers/question.py
> +class State(Enum):
Добавил auto()

2024-02-05 23:29 UTC, Maxuz commented on askbot/room.py
> +    return list(Room.objects.filter(is_visible=True, chat_id__isnull=False).all())
Done

2024-02-14 17:03 UTC, vas3k commented on askbot/handlers/question.py
> +        "Сейчас твой вопрос выглядит так: \n\n"
Да, и эти самые маленькие тоже наверн. И используй HTML рендер по-умолчанию, а не Markdown, с ним много проблем. Плюс, темплейты позволят экранировать пользовательский ввод на случай если кто-то захочет туда сам вставить HTML. А сейчас прямо в этом месте будет небольшой XSS

2024-02-14 17:06 UTC, vas3k commented on askbot/models.py
> +    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL) # TODO discuss on_delete action
Мы никогда не удаляем user, мы удаляем все данные, но оставляем запись с ID (aka tombstone). Так что пофиг, можно делать SET_NULL и надеяться, что это никогда не произойдет

2024-02-14 17:12 UTC, vas3k requested changes
Покомментил

И еще одно общее: мне не очень нравится название AskBot и моделей типа AskUser. Ask — это глагол, потому во всех случаях это читается как "спросить юзера" и нифига не понятно

Так что принимаю предложения как еще лучше перевести название "Вастрик.Справочная" на английский, чтобы всем всё было понятно и использовалось существительное

2024-02-15 00:17 UTC, Maxuz commented on askbot/models.py
> +    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL) # TODO discuss on_delete action
done

2024-02-16 01:28 UTC, Maxuz commented on askbot/handlers/question.py
> +        "Здравствуй добрый человек 🤗\n\n\n"
Done

2024-06-14 14:47 UTC, vas3k approved these changes
👍

2024-06-14 14:52 UTC, merged