feat: per-user RSS feed
vas3k/vas3k.club pull request #1232
Opened 2024-07-11 15:43 UTC by aigoncharov

Добавляет RSS фид из постов клубчанина. См. #1231 

# Как тестил

1. Накатил постов для теста с помощью `docker exec -it club_app python3 manage.py import_posts_to_dev`
2. Проверил, что RSS фид всех постов работает (правильная ссылка и открывается нужная xmlка)
    ![image](https://github.com/vas3k/vas3k.club/assets/12794628/5448648f-0c87-4f43-9b9d-13576f113658)
3. Проверил, что RSS фид для юзера работает (правильная ссылка и открывается нужная xmlка)
    ![image](https://github.com/vas3k/vas3k.club/assets/12794628/40239457-f08b-4196-a66c-8a8165562b54)
4. Проверил, что если в урле для пользовательского RSS фида вместо имени пользователя написать хрень, то будет 404

2024-07-11 15:56 UTC, trin4ik commented on posts/rss.py
> +        print("newsPostsRss {}".format(user_slug))
Кажется, это с дебага

2024-07-11 15:56 UTC, trin4ik commented on posts/rss.py
> +        return "/user/{}/posts.rss".format(user.slug)
Приняли, что строки передаём в современном формате, т.е. не 
`return "/user/{}/posts.rss".format(user.slug)`
а
`return f"/user/{user.slug}/posts.rss"`

2024-07-11 16:07 UTC, igoose1 commented on posts/rss.py
> +           .filter(is_approved_by_moderator=True)
Кстати, не знаю, насколько это может быть ожидаемое поведение для тебя, но вот этот фильтр (is_approved_by_moderator) может быть причиной, почему ты какие-то посты каких-то людей в RSS не увидишь. Некоторые посты не аппрувятся, но и не реджектятся: например, мемопосты или что-то не совсем плохое, но и не совсем хорошее.

Просто пишу это, чтобы было ожидание, что посты в RSS пользователя могут не совпадать со списком постов пользователя на веб-странице.

2024-07-11 17:41 UTC, aigoncharov commented on posts/rss.py
> +           .filter(is_approved_by_moderator=True)
Тут я просто оставил как было. Не знаешь толком что это - не трогай :)
Спасибо, что рассказал!

2024-07-12 08:49 UTC, vas3k requested changes

2024-07-12 14:34 UTC, aigoncharov commented on frontend/html/users/profile.html
> +{% block rss %}
@vas3k часть RSS клиентов не любят, когда несколько фидов прилинковано на страницу. Берут рандомный по мановению пятки левой ноги. Я бы предложил заменять. Могу поправить если настаиваешь.

Второй коммент поправил.

2024-07-12 16:45 UTC, vas3k commented on frontend/html/users/profile.html
> +{% block rss %}
Ну ладно, поверю. На моем опыте таких проблем не встречал

2024-07-12 16:45 UTC, vas3k approved these changes
Во, ну намного же чище стало!

2024-07-12 16:50 UTC, merged

2024-07-13 05:45 UTC, aigoncharov commented on frontend/html/users/profile.html
> +{% block rss %}
Я с этим столкнулся, когда конвертер [телеги в рсс делал](https://github.com/aigoncharov/telegram-to-rss). Там куча фидов на домашней странице.