feat: added theme switcher with match-system option
vas3k/vas3k.club pull request #1273
Opened 2024-11-25 17:28 UTC by kirill-dev-pro

<img width="233" alt="image" src="https://github.com/user-attachments/assets/65c107c8-bc24-4a54-ad63-6afdf6f30e4b">

<img width="300" alt="image" src="https://github.com/user-attachments/assets/83015212-b32b-4272-b97b-d6d3f987356e">

2024-11-26 08:50 UTC, nlopin commented
привет! а мы не можем то же самое на Vue сделать? Я не помню, чтобы мы WebComponents использовали во фронтенде и если это первый случай, я бы предпочел не размывать тех.стек и сделать все на вью.

2024-11-26 12:11 UTC, trin4ik reviewed
Спасибо за PR, многое из ревью из категории "разрешите доеб*ться"

2024-11-26 12:11 UTC, trin4ik commented on frontend/html/misc/theme_switcher.html
> +        console.log('picker', picker);
Надо бы кильнуть, пакер не убирает логи из продакшен-бандла

2024-11-26 12:11 UTC, trin4ik commented on frontend/html/misc/theme_switcher.html
> +      this.querySelector('select')?.addEventListener('change', (e) => {
Зачем тут nullsafe?

2024-11-26 12:11 UTC, trin4ik commented on frontend/html/misc/theme_switcher.html
> +        if (e.currentTarget instanceof HTMLSelectElement) {
событие `change`, прослушиваемое на `select` теге всегда же будет возвращать этот самый селект как `target`, зачем проверять?

2024-11-26 12:15 UTC, trin4ik commented on frontend/html/misc/theme_switcher.html
> +        }
![image](https://github.com/user-attachments/assets/d986d957-3be5-4888-a246-31bf4f970452)

2024-11-28 20:07 UTC, vas3k requested changes
Минус эстетика это минус вайб! Надо подумать как текущий контрол адаптировать под три положения, а не пытаться заменить на старый советский селект :)

2024-12-06 14:01 UTC, kirill-dev-pro commented
@vas3k Текущий контрол это checkbox, у него по определению не может быть 3 положений

2024-12-21 16:42 UTC, nlopin commented
> Текущий контрол это checkbox, у него по определению не может быть 3 положений

У чекбокса есть indeterminate state сейчас
![CleanShot 2024-12-21 at 17 41 53@2x](https://github.com/user-attachments/assets/1a75c73d-e359-4f1c-bd14-d4e8d4967bca)

2024-12-24 22:21 UTC, trin4ik commented
Чеклист перед мержем в мастер:
- [ ] Перевести стили компонента из px на em, сейчас всё в px и может прыгать в разных браузерах
- [ ] Проверить в мобилках, на мелких экранах компонент может расподаться, ему нужен nowrap или родителю
- [ ] Присутствие `this.$forceUpdate` в целом обоснованно и не напрягает, но можно обойтись и без него. Оставить его тут или обойтись без него -- на усмотрение @nlopin, наверно. Я бы оставил, тут оно не мешает.

2024-12-25 22:19 UTC, nlopin commented on frontend/static/js/components/ThemeSwitcher.vue
> +        if (typeof localStorage !== "undefined") {
мы точно хотим поддерживать браузеры без локалстореджа? он с 2010 года браузерами поддерживается

2024-12-25 22:25 UTC, nlopin approved these changes
Кайф. Наверное можно `forceUpdate` заменить на компьютед поле, но у нас этот компонент ничего кроме себя не рендерит, так что можно остановиться на текущем варианте

2024-12-26 04:42 UTC, trin4ik commented on frontend/static/js/components/ThemeSwitcher.vue
> +        if (typeof localStorage !== "undefined") {
> мы точно хотим поддерживать браузеры без локалстореджа? он с 2010 года браузерами поддерживается

я бы тоже убрал эти проверки, +1

2024-12-26 04:58 UTC, trin4ik commented
> Кайф. Наверное можно `forceUpdate` заменить на компьютед поле, но у нас этот компонент ничего кроме себя не рендерит, так что можно остановиться на текущем варианте

Форсуапдейт нужен только в случае, когда меняется именно системная тема. Т.е. без него всё прекрасно работает, но если переключить системную тему, в браузере ничего не поменяется, хотя метод дёрнется. Идея в том, что в этом методе не произойдёт мутации, изменения стейта, поэтому и не произойдёт ререндера. Т.е. когда свичер в положении "авто", данный метод не меняет ничего в стейте, ну ты понял. 
Я помог Кириллу с кодом и как раз хотел показать как именно работать с компьютедами, с методами, с вочами итп и всё шло хорошо, пока не проверил "auto" положение и смену системной темы ) 
Избавиться от форсапдейта можно отказавшись от метода realTheme, вынеся этот параметр в компьютед или в дату. Но как-будто тут это вообще не актуально, в том плане, что тут нет миллиона ререндеров, это не влияет на производительность итп.

2025-01-31 07:50 UTC, nlopin commented
Подправил стили:
Десктоп ![CleanShot 2025-01-31 at 08 48 56@2x](https://github.com/user-attachments/assets/a864845f-6356-438f-a466-7f80e265cbd4)

На узком экране выбор темы и кнопка выхода показываются отдельным рядом, а не второй колонкой
![CleanShot 2025-01-31 at 08 49 23@2x](https://github.com/user-attachments/assets/2719ea9f-4cd3-438c-bff3-cc8f7bd8f2e3)

2025-02-04 11:53 UTC, vas3k requested changes
Теперь интерфейс мигает при каждом открытии страницы в черной теме 


https://github.com/user-attachments/assets/8dbeebb3-4a45-4412-8b0d-f2961b9d9b1b

2025-02-04 11:57 UTC, vas3k commented
Скорее всего мигание связано с тем, что ты удалил из head инициализацию темы и перенес ее в JS-компонент. Он потому там и лежал, чтобы отрабатывать ДО рендеринга страницы, а не после :)

Так что либо оставляем все там, либо придумываем способы как этого избежать

2025-02-10 08:22 UTC, nlopin commented
> Скорее всего мигание связано с тем, что ты удалил из head инициализацию темы и перенес ее в JS-компонент. Он потому там и лежал, чтобы отрабатывать ДО рендеринга страницы, а не после :)
> 
> Так что либо оставляем все там, либо придумываем способы как этого избежать

вернул кусок, связанный с установкой стартовой темы. После инициализации тему подхватывает вью

2025-02-10 10:55 UTC, vas3k approved these changes
На локалхосте все равно иногда (1 раз из 7) мигает, но сошлемся на дев-билд вебпака, может на проде не будет такого...

2025-02-10 10:55 UTC, merged