Normalize available comment actions
vas3k/vas3k.club pull request #278
Opened 2020-06-14 15:32 UTC by hudochenkov

Fixes #276.

Что-то я ваш  Python и Jinja не пойму. Не дает использовать `()` в условиях, чтобы группировать логику.

Например:

```python
if comment.author == me and comment.is_editable or me.is_moderator
```

Это так?

```python
if (comment.author == me and comment.is_editable) or me.is_moderator
```

Или вот так?

```python
if comment.author == me and (comment.is_editable or me.is_moderator)
```

Что делать, если мне нужно то, или иное поведение в зависимости от группировки?

Из-за этого пришлось делать вложенные условия для удаления комментариев.

2020-08-29 21:33 UTC, skywinder commented
@hudochenkov привет. Какой статус фикса? Нужно помочь с логикой?

2020-08-29 21:39 UTC, hudochenkov commented
@skywinder фикс готов был с самого начала :) Возможно условия можно улучшить. Если знаешь как — можешь в моем форке изменить.

2020-08-29 22:24 UTC, skywinder commented
> @skywinder фикс готов был с самого начала :) Возможно условия можно улучшить. Если знаешь как — можешь в моем форке изменить.

Я с телефона на выходных. Но оставил комент к вложенной штуке как сделать без вложенности и даже без скобок :)

Кстати, для красоты можно по строчкам разбить, как тут сделано: https://stackoverflow.com/a/15168895

2020-08-29 22:34 UTC, skywinder commented
А так логика и приоритет операторов в питоне и баше и других языках одинаковая. 

Команды без скобок выполняются слева на права и кладутся в стек. 

Те
Если слева true, след or не выполняется. 
Если false , следующий and и все после не выполняется.

Исключение - если там не просто параметры, а функции. Вот функции все равно выполнятся (@vas3k, ты питонщик, поправь если что)

Но в любом случае на конечную логику and/or это не влияет (ЕСЛИ ФУНКЦИИ ЧИСТЫЕ)

2020-08-29 22:38 UTC, skywinder commented
Соответсвенно в твоих примерах:
Первый и второй вариант аналогичны. 
А третий нет. (Он сработает только если ты модератор или комент editable)

2020-08-29 22:48 UTC, skywinder requested changes

2020-08-31 22:37 UTC, hudochenkov commented on frontend/html/comments/types/battle.html
> +        {% if me == comment.author and comment.is_deletable or me == comment.post.author or me.is_moderator %}
На `and or` парсер ломается. Исходя из логики https://github.com/vas3k/vas3k.club/pull/278#issuecomment-683348955 я заменил `and or` на `and`.

2020-08-31 22:40 UTC, hudochenkov commented on frontend/html/comments/types/reply.html
> -        {% if comment.author == me and comment.is_editable or me.is_moderator %}
Тут, получается, логика была изначально неправильная. Т. к. проверка на `me.is_moderator` была бы только, если `comment.author == me` true.

2020-08-31 22:42 UTC, hudochenkov commented
@skywinder спасибо за разъяснения. Все исправил.

Не знаю почему билд ломается, я в докере ничего не понимаю. Локально все работает. Может потому что ветка старая?

2020-08-31 22:46 UTC, hudochenkov commented
@vas3k я заметил, что автор поста может удалять _не свои_ комментарии `battle`, `bold`, `normal`, но не может `reply`. Так и задумано? Почему автор поста может удалять чужие комментарии? А почему не может удалить `reply`?

2020-09-01 05:58 UTC, vas3k commented
Да, так задумано. С реплай это баг

2020-10-07 16:35 UTC, skywinder commented on frontend/html/comments/types/reply.html
> -        {% if comment.author == me and comment.is_editable or me.is_moderator %}
Не, она идет по and / or до конца. 
1) если последний результат был true, то пропускаются or (тк при любом раскладе это не меняет ответ), но проверяет or.

И наоборот. если fasle -  то пропускаются and, но заходит в проверки or.

 тут все правильно сработает.

2020-10-07 16:36 UTC, skywinder commented on frontend/html/comments/types/reply.html
> -        {% if comment.author == me and comment.is_editable or me.is_moderator %}
для примера можешь в питоне запустить:
```>>> print( False & False | True)
>>> print( False & True | True)```

2020-10-07 16:41 UTC, skywinder commented
О,  супер!
Вот теперь красота! По ходу можно мержить
 kindly check @vas3k

2020-10-07 16:42 UTC, skywinder approved these changes

2020-10-07 16:51 UTC, vas3k commented
А что изменилось?

2020-10-07 16:59 UTC, skywinder commented
теперь оно работает и правильна логика
2087ae3 и  8a6e7bc

2021-04-07 18:19 UTC, closed without merging