issue#367: posts links in profile comments list
vas3k/vas3k.club pull request #385
Opened 2020-08-31 20:59 UTC by fr33mang

close #367 

Вот так:
![image](https://user-images.githubusercontent.com/13254668/91767899-8b941f80-ebe5-11ea-83a5-da1423d88c0b.png)

2020-09-01 08:39 UTC, vas3k requested changes
Не, тут нельзя заменять имя автора на название поста. Этот виджет универсален и используется в других местах (например в поиске), там это может выводить в заблуждение. Нужно думать над UI в целом, а не фиксить заплатками :)

2020-09-01 08:42 UTC, fr33mang commented
Я подумал, что для поиска тоже норм🤔

Тогда мб кто-то предложит, как это красиво сделать, либо можем отказаться от универсального шаблона.

2020-09-01 08:45 UTC, vas3k commented
Я бы не плодил сущности без необходимости, а сел и подумал. Щас сам не могу, потому делегирую это умным людям здесь :)

2020-10-11 22:07 UTC, devcooch commented
Пара альтернативных предложений:
Название поста с ссылкой перед комментом (игнорировать вёрстку, пока только идейно обсуждаем):
![image](https://user-images.githubusercontent.com/2089015/95691332-add67f80-0c1e-11eb-823d-e61a7f16fad4.png)
Можно группировать по посту, можно нет.
Либо в хедере конкретного коммента:
![image](https://user-images.githubusercontent.com/2089015/95691356-d65e7980-0c1e-11eb-8cae-45d0a485069a.png)
Там правда чуть сложнее реализовывать, ибо сейчас вся зона комментария это одна большая ссылка.

2020-10-12 03:20 UTC, skywinder commented
+ за предложеный вариант. я бы еще поменял местами только дату и название поста, тогда чуть логичнее будет

2020-10-12 03:23 UTC, skywinder commented
@devcooch думаю это логичнее обсудить в основной таске #367 

@fr33mang что думаешь по такому дизайну?

2020-11-05 20:06 UTC, closed without merging