issue #397: fix weekly digest intros html escaping
vas3k/vas3k.club pull request #403
Opened 2020-10-02 17:04 UTC by fr33mang

#397

2020-10-02 17:38 UTC, fr33mang commented
если заюзать description вместо text, то магическим образом исчезает часть переходов на новую строку. 

Это связано наверно с преобразованиями внутри метода description.

2020-10-02 22:16 UTC, vas3k commented
Ты использовал магию. Лучше найди причину и пофикси ее, а не лепи хаки. Метод description тут не подходит

2020-10-02 22:16 UTC, vas3k requested changes
Магия

2020-10-05 14:06 UTC, fr33mang commented
> Магия

А поясни плиз, как будет без магии примерно?
Мне казалось, что предыдущая реализация еще более магическая 🤔

2020-10-05 14:09 UTC, vas3k commented
Предыдущая реализация берет исходник текста поста, превращает его в маркдаун, обрезает. Всё. Где-то на этом пути ломается эксейпинг.

Ты же используешь метод description. Он в свою очередь: берет отрендеренный html из кеша поста, вырезает из него теги, обрезает по длине. Это no-brainer тупой вариант генерить превьюхи для телеграма. Больше он ни для чего не годится. Ты же теперь: берешь этот дважды пережеванный HTML с вырезанными тегами, превращаешь его в Markdown (ЗАЧЕМ?), потом обрезаешь еще раз. Так не годится. Ты скрываешь проблемы вместо того, чтобы найти и починить ее

2020-10-05 14:17 UTC, fr33mang commented
> Ты же используешь метод description

Стоп, я же наоборот выпилил использование метода description :(

2020-10-05 14:18 UTC, vas3k commented
Бляяя. Я ебусь в глаза, извини. Перепутал до и после. Нужно больше отдыхать

2020-10-05 14:18 UTC, vas3k approved these changes

2020-10-05 14:18 UTC, merged