issue#416: Fixed styles in notifications page
vas3k/vas3k.club pull request #417
Opened 2020-10-07 12:08 UTC by aiserg

### **Before:**

![image](https://user-images.githubusercontent.com/6620176/95328525-58147700-08ae-11eb-88ac-180caffa8660.png)
![image](https://user-images.githubusercontent.com/6620176/95328701-9c077c00-08ae-11eb-8fe2-05fbd53da88d.png)

### **After:**

![image](https://user-images.githubusercontent.com/6620176/95328581-6cf10a80-08ae-11eb-9c20-5cf56403680c.png)
![image](https://user-images.githubusercontent.com/6620176/95328611-77ab9f80-08ae-11eb-9fba-cfd54d0c223e.png)
![image](https://user-images.githubusercontent.com/6620176/95328649-872ae880-08ae-11eb-926e-abef4db22ccd.png)

2020-10-07 13:56 UTC, vas3k requested changes

2020-10-07 13:56 UTC, vas3k commented on frontend/static/css/theme.css
> +        --block-shadow-hover: 2px 2px 8px 0 rgba(69, 70, 70, 0.12);
Хммм. А расскажи в чем идея вводить новые глобальные переменные и потом использовать их в одном узком кейсе? Тогда уж либо везде, либо хардкодь прям в класс :)

2020-10-07 14:11 UTC, aiserg commented on frontend/static/css/theme.css
> +        --block-shadow-hover: 2px 2px 8px 0 rgba(69, 70, 70, 0.12);
@vas3k Здесь конкретно удобно использовать в зависимость от темы – в dark mode тень не нужна
Но вообще да, увидел, лучше захардкодить

2020-10-09 10:57 UTC, vas3k approved these changes

2020-10-09 10:57 UTC, merged