Скрывание постов в закладках, которые были помещены в черновики
vas3k/vas3k.club pull request #430
Opened 2020-10-15 15:05 UTC by aiserg

Скрываем посты в закладках, которые авторы поместили в черновики и теперь не доступны для прочтения

Возможно было бы лучше помечать его как скрытый, а не убирать совсем 🤔

2020-10-16 11:22 UTC, vas3k requested changes
Не, давай лучше фильтровать is_visible=False прямо на уровне ORM во вьюхе. Перекладывание этой логики на фронтенд запросто сломает пажинацию и вообще логически неверно.

Там есть кверисет .visible_objects(), обычно он везде используется, проверь почему там нет.

2020-10-20 14:52 UTC, aiserg commented
@vas3k Точно, спасибо, поправил 👍

2020-10-21 13:29 UTC, vas3k commented on bookmarks/models.py
> +    @classmethod
А зачем делать visible_objects() в PostBookmark, если ты все равно используешь его только из Post? :)

2020-10-21 14:19 UTC, aiserg commented on bookmarks/models.py
> +    @classmethod
@vas3k Упс, оно там было, сорян, стер

2020-10-21 15:07 UTC, vas3k approved these changes
Вот теперь норм! Кратко и красиво :)

2020-10-21 15:08 UTC, merged