Adding possibility to delete unpublished post
vas3k/vas3k.club pull request #431
Opened 2020-10-15 22:38 UTC by devcooch

Закрывает #174 .
Удалить можно только никогда не опубликованный пост.

2020-10-16 11:26 UTC, vas3k requested changes
Вижу две проблемы:

1. Люди моментально запутаются почему какие-то черновики можно удалять, а какие-то нельзя, и засрут этими вопросами все лички, до которых дотянутся :)
2. Я за софт-дилит постов. Прайваси здесь не так важно, как защита от человеческой глупости или импульсивности. Полную очистку будем делать уже при удалении акка. Так что давай сделаем флаг в БД типа deleted_at: datetime. Посмотри как в комментах, вот примерно так же, только не надо хранить deleted_by.

2020-10-19 22:26 UTC, devcooch commented
![Кнопка удаления](https://user-images.githubusercontent.com/2089015/96518222-beb07200-126a-11eb-9439-6ad96e20e5c6.png)
![Меню с корзиной](https://user-images.githubusercontent.com/2089015/96518240-c96b0700-126a-11eb-868c-a784e31bea38.png)
![Внутри корзины](https://user-images.githubusercontent.com/2089015/96518253-cff97e80-126a-11eb-80d9-15c7c874f99f.png)
![Восстановление](https://user-images.githubusercontent.com/2089015/96518272-dd166d80-126a-11eb-9246-61e6a5a8339c.png)

2020-10-19 22:27 UTC, devcooch commented
Удалить кстати можно только черновик

2020-10-26 10:36 UTC, vas3k approved these changes
UI пока не тестил, но код збс 👍

2020-10-26 10:36 UTC, merged