Render comments on client
vas3k/vas3k.club pull request #442
Opened 2020-10-25 19:13 UTC by nlopin

Related to #332 

## Что

Перенос отрисовки комментариев с сервера на клиент

[Видео демка](https://www.loom.com/share/ed1abcf179b74f32a2588d95c3233359)

## Зачем

Сделать комментарии асинхронными и перестать обновлять страницу при добавлении комментария. Подбробности в #332 

## Как

* сервеные шаблоны удалены, кроме шаблоны для отрисовки комментария на странице поиска. Теперь только фронтенд знает, как рендерить комментарии. 
* сервер рендерит Vue компонент и устанавливает все нужные props

2020-10-25 19:17 UTC, nlopin commented on comments/templatetags/comments.py
> +def unsafe_render_comment(context, comment):
Вот с этим решением я не уверен, дайте обратную связь.

Проблема: если во vue компонент вставлять комментарий, полученный из `mark_safe`, браузер распознает в нем html и рендерит его. При этом vue компонент разламывается. 

Решение: не делать `mark_safe`. Мне оно кажется не очень, но другое решение я не нашел

2020-10-30 10:09 UTC, vas3k commented on comments/templatetags/comments.py
> +        "createdAt": str(cool_date(comment.created_at)),
Доебусь до нейминга :) Я понимаю, это тема для холивара, навай везде использовать названия с подчеркиваниями (snake case) везде — `created_at`, `full_name`, `hours_to_retract`, итд. Потому что во-первых это будет консистентно с нашими имеющимися JSON API, а во-вторых такой подход рекомендован в некоторых популярных гайдлайнах. Например: https://opensource.zalando.com/restful-api-guidelines/#118

2020-10-30 10:10 UTC, vas3k commented on comments/templatetags/comments.py
> +def unsafe_render_comment(context, comment):
А зачем нам тогда здесь mark_safe вообще?

2020-10-30 10:12 UTC, vas3k commented on comments/templatetags/comments.py
> +        "createdAt": str(cool_date(comment.created_at)),
Ах да, в самом JS коде уже можешь маппить их на более привычный camelCase, тут проблем нет

2020-10-30 10:16 UTC, vas3k approved these changes
Оставил пару комментов, остальное вроде нравится. Было бы хорошо протестировать это на каком-нибудь большом треде с кучей комментов чтобы понять производительность. Пока нажму аппрув чтобы тебе хактоберфест засчитало :D

2020-10-30 11:56 UTC, nlopin commented on comments/templatetags/comments.py
> +def unsafe_render_comment(context, comment):
`mark_safe` нужен, чтобы джанго мог рендерить свои темплейты. Мы все еще рендерим комменты на сервере для поиска и профиля. 

Можно подумать о нейминге, потому что `mark_safe` это сигнал джанго не эскейпить html-символы. В этом смысле `unsafe_render_component` не делает ничего небезопасного. Такое имя я выбрал, чтобы не ломать остальные шаблоны и не раздувать этот PR

2020-12-30 08:17 UTC, vas3k requested changes
Помечу теперь красненьким чтобы выделить необходимость обновления этого PR :) Там еще и треды с третьим уровнем вложенности появились за это время.

2021-04-25 21:30 UTC, nlopin commented
Давай-ка я это закрою, чтобы потом если что восстать из пепла

2021-04-25 21:30 UTC, closed without merging