Fixing error messaged for editing or deleting a comment
vas3k/vas3k.club pull request #548
Opened 2021-02-05 20:08 UTC by devcooch

2021-02-12 08:40 UTC, vas3k commented on comments/views.py
> +                message=f"Комментарий можно редактировать только в первые {settings.COMMENT_EDIT_TIMEDELTA} часа после создания"
Может все-таки использовать тут settings.COMMENT_EDIT_TIMEDELTA.minutes, а не полагаться на магию конвертации объектов в стринги?

2021-02-12 08:40 UTC, vas3k commented on comments/views.py
> +                message=f"Комментарий можно удалить только в первые {settings.COMMENT_DELETE_TIMEDELTA//365} лет после создания"
А тут .days // 365

2021-02-12 08:40 UTC, vas3k requested changes
up

2021-02-22 22:12 UTC, devcooch commented
Чот не понял, что я сделал не так. Был в старой ветке, вмержил мастер, добавил фикс сверху, но почему мерж тут показан???

2021-06-14 20:26 UTC, devcooch commented
Создам новую версию

2021-06-14 20:26 UTC, closed without merging