фикс #474 "При реплае на коммент сбрасывается comment_order"
vas3k/vas3k.club pull request #551
Opened 2021-02-08 09:59 UTC by nitrok

2021-02-12 08:45 UTC, vas3k requested changes

2021-02-12 08:45 UTC, vas3k commented on comments/forms.py
> +    post_comment_order = forms.CharField(widget=forms.HiddenInput())
А точно без расширения формы тут не обойтись? Здравый смысл подсказывает мне, что если ты просто попробуешь получить `request.POST.get("post_comment_order")`, все сработает так же хорошо

2021-02-15 05:36 UTC, nitrok commented on comments/forms.py
> +    post_comment_order = forms.CharField(widget=forms.HiddenInput())
Спасибо, убрал поле из форм.

2021-02-21 09:06 UTC, vas3k approved these changes

2021-02-21 09:09 UTC, merged