Уведомления в телеграм о выданных плашках
vas3k/vas3k.club pull request #664
Opened 2021-08-16 14:58 UTC by devcooch

2021-08-16 17:11 UTC, vas3k requested changes

2021-08-16 17:11 UTC, vas3k commented on common/data/labels.py
> +NOTIFY_LABELS = ["approved", "inside", "thread", "comments", "top_week", "wow", "drama", "essential"]
Давай уведомлять о всех лейблах. Этот список точно проебём или забудем

2021-08-16 17:11 UTC, vas3k commented on notifications/telegram/templates/messages/post_label.html
> +😲😲😲 Вот это да! Ваш пост «<a href="{{ settings.APP_HOST }}{% url "show_post" post.type post.slug %}">{{ post.title }}</a>» получил плашку качества «{{ post.label["title"] }}».
Предлагаю более нейтральный вариант "🎉 Ваш пост Х получил плашку Y. Поздравляем!"

2021-08-19 06:00 UTC, vas3k commented on notifications/views.py
> -        .exclude(label__isnull=False, label__code="ad")\
А почему удалил тут? Теперь индекс в БД не сработает и будет сканировать каждый пост

2021-08-19 06:04 UTC, vas3k commented on notifications/views.py
> -        .exclude(label__isnull=False, label__code="ad")\
А, я понял, ты хотел переедлать на label_code? Тогда обрати внимание на два подчеркивания :) Ты обращаешься к удалённому полю щас. Ну и проблема с индексом тоже останется, постгресу надо явно говорить isnull=false чтобы он пропустил пустые

2021-08-20 18:29 UTC, devcooch commented on notifications/views.py
> -        .exclude(label__isnull=False, label__code="ad")\
Done

2021-08-23 10:19 UTC, vas3k approved these changes

2021-08-23 10:20 UTC, merged