draft #225 автокомплит для меншенов
vas3k/vas3k.club pull request #685
Opened 2021-09-04 12:05 UTC by andresokol

(как-то так, нужен дизайн)

![Screen-Recording-2021-09-04-at-14 59 04](https://user-images.githubusercontent.com/5289588/132093818-6b8e186e-5a0b-4e17-9f60-b4dc4ab1e8cc.gif)

2021-09-23 10:57 UTC, vas3k commented on club/urls.py
> +    path("users/suggest/", suggest_users, name="users_suggest"),
Долго думал как тут рализовать APIху чтобы она была в стиле всех остальных наших эндпоинтов. Потому ревью PR заняло так долго времени. Сейчас это просто случайный URL, а я очень трепетно отношусь к чистоте публичных интерфейсов, потому что знаю как быстро они превращаются в месиво говна и палок.

Предлагаю здесь не изобретать новый эндпоинт, а использовать `/search/`. Наши апихи строятся по принципу "URL реальной страницы" + суффикс ".json" + GET-параметры, так что конкретно тут будет следующий эндпоинт: `/search.json?q=ABC&type=user`. Что лакончино вписывается в имеющуюся структуру: https://vas3k.club/search/?q=vas3k&type=user

Посмотри как сделаны другие API на сайте, у них отдельные файлы api.py даже есть. Можно пока реализовать частный случай только для юзеров. Там даже есть объект юзера уже готовый, чтобы ты не переизобретал JSON.

Если не понял или не разобрался — я могу сам сделать, но это займет время

2021-09-23 11:00 UTC, vas3k requested changes
Давай еще раз повторю логику работы, я писал ее в тикетах, но кажется ты пропустил:

0. На странице ведётся кеш всех известных slug'ов. При загрузке в него кладутся все slug'и юзеров из всех комментов, которые уже есть на странице + slug авторов поста.
1. Когда юзер набирает символ "@", срабатывает автоподстановка по этому кешу. Никакого запроса на API не происходит. Это логика гитхаба, он так и делает. Попробуй сейчас в комментах набрать "@"
2. Когда юзер набрал 3 символа после "@", то уже улетает запрос на поиск по префиксу. Добавлять их в кеш или нет — уже дело твое. Но идея в том, что ты не DDoS'ишь себя запросами на /suggest/ по миллиарду в секунду.

2021-09-23 11:25 UTC, vas3k commented on club/urls.py
> +    path("users/suggest/", suggest_users, name="users_suggest"),
А, хотя я понял что тебя смутило, у нас есть /upvote/ и прочие костыльные ендпоинты с какими-то ужасными флагами is_ajax. Короче, их можно считать олдскулом

2021-09-23 13:42 UTC, vas3k commented on club/urls.py
> +    path("users/suggest/", suggest_users, name="users_suggest"),
Блин, попытался сделать как сам сказал, нифига не получилось :D Буду еще мучаться с эндпоинтом, забей пока, давай фронтовую логику допилим

2021-10-30 16:36 UTC, vadik49b commented
Привет. Прочитал пост в клубе и взялся доделать меншены. Подойдёт ли такой дизайн слизаный у GitHub?

https://user-images.githubusercontent.com/3475948/139541218-66806a98-f1de-4450-b76a-0e53d3beade1.mov

Я пока ещё вожусь с `EasyMDE`, хочется сделать [автодополнение через выделение](https://ilyabirman.ru/meanwhile/all/autocomplete-style/).

Мне осталось сделать локальный кеш и как-нибудь покрасивее связать `EasyMDE` и Vue. @vas3k ты сейчас инициализируешь `EasyMDE` руками в `main.js` и из-за этого не понятно как получить в `App.js` истанс Vue. Возможно стоит перенести инициализацию в отдельную Vue компоненту `<invisible-markdown-editor/>`.

2021-11-01 10:58 UTC, vas3k commented
> Возможно стоит перенести инициализацию в отдельную Vue компоненту <invisible-markdown-editor/>.

Думали, отказались. Проблема в том, что тогда каждое текстовое поле на странице будет ждать инициализации JS. Это заметный лаг в несколько секунд. Это плохо, никто так и не решил эту проблему. Так что я все-таки за обычную textarea, которая прогрессивно превращается в редактор. В идеале, конечно, чтобы она сначала была текстареей, а потом становилась vue-компонентой, но я хз можно ли так.

2021-11-01 11:00 UTC, vas3k commented
@vadik49b 

> Подойдёт ли такой дизайн слизаный у GitHub?

Я бы убрал оттуда position и выводил бы прям как это делает гитхаб: "@vas3k Вастрик". Можно добавить аватарку маленькую еще перед ником, но наверное они будут постоянно загружаться и все портить.

2021-11-01 15:29 UTC, vadik49b commented
> Я бы убрал оттуда position и выводил бы прям как это делает гитхаб. 

<img width="326" alt="Screen Shot 2021-11-01 at 11 26 27 AM" src="https://user-images.githubusercontent.com/3475948/139696838-89898603-bebc-47aa-8b5b-181becec3acd.png">

@vas3k что ты имеешь в виду под position? Я не вижу отличий от гитхаба.

2021-11-01 15:31 UTC, vas3k commented
@vadik49b а, я думал у тебя серый текст это то, что пишется в комментах после имени. Типа "должность". Тогда все правильно, да

2021-12-15 11:39 UTC, ninedev-i commented
@vas3k можно закрывать, сделано [здесь](https://github.com/vas3k/vas3k.club/pull/770)

2021-12-15 12:06 UTC, closed without merging