[feature] Скроллинг по непрочитанным комментариям + кнопка «наверх»
vas3k/vas3k.club pull request #707
Opened 2021-10-03 16:23 UTC by Zhurbin

**Issue:** https://github.com/vas3k/vas3k.club/issues/491

**ПР использует механику уже существующего скроллинга комментариев кнопками ctrl-up/down, которую реализовал @simnv :** https://github.com/vas3k/vas3k.club/pull/663

**Что я добавил/изменил:**
- Добавил кнопку со стрелкой на страницах, где есть комментарии (логика реализации: https://github.com/vas3k/vas3k.club/issues/491#issuecomment-932042851)
- Перенёс логику скролла  кнопками ctrl-up/down (initializeCommentScroll) в компонент (практически as is, без изменений)
- Поменял доскролл к низу страницы на доскролл к полю комментирования
- Починил анимацию подсвечивания коммента, к которому подскролл (оставил как было blink анимацию, пишите если есть предложения как улучшить)
- Вынес функцию throttle в utils, т.к. она стала переиспользуемой

**Видео:**

https://user-images.githubusercontent.com/5123981/135762492-1b41d3f0-bf39-4a22-8a40-b9fad7c07031.mov

2021-10-03 17:06 UTC, simnv commented
Мне нра.

Нашёл, кстати, почему скролл иногда прыгает не туда: если между текущей позицией и позицией, куда прыгаем, есть комментарии с картинками. Все картинки тут с ленивой загрузкой (`loading="lazy"`), и их размер становится известен только в момент появления в окне. Можно, например, найти все картинки между текущей и целевой позициями, пнуть их загрузку, заменить кнопку на индикатор загрузки, а после загрузки (`complete==true`) прыгнуть. Надо только продумать, что делать с тормозной загрузкой.

2021-10-03 18:31 UTC, vas3k commented
Крутяк! Наконец-то! Пошел тестить на локале. Пара замечаний сразу (у меня Firefox если вдруг это важно):

1. Первый клик всегда уносит куда-то не туда. Он должен уносить до хеша #comments, а сейчас как-то случайно отматывает до до середины поста, до далеко вниз. Давай отключать `loading="lazy"` для картинок тогда, раз уж без него невозможно сделать нормально.
2. Я попробовал отключить`loading="lazy"`. Не помогло. Надо еще тестить на реальных данных, короче. Хочешь сделаем какой-нибудь флаг в URL чтобы включать эту кнопку и потестим на продакшене? Я знаю как тяжело бывает воспроизвети на локалхосте.
3. При достижении конца в идеале бы менять иконку на стрелочку наверх. Сейчас прям сильно бросается в глаза :)

В остальном заебись. По коду и анимациям мне нравится. Скорее бы доделать и задеплоить! (надо будет еще мобилу проверить)

2021-10-03 18:55 UTC, Zhurbin commented
> 1. Первый клик всегда уносит куда-то не туда. Он должен уносить до хеша #comments, а сейчас как-то случайно отматывает до до середины поста, до далеко вниз. Давай отключать `loading="lazy"` для картинок тогда, раз уж без него невозможно сделать нормально.

Это именно та же проблема с изменением высоты страницы после подгрузки картинок? Или у тебя воспроизводится и на полностью подгруженных img?

> 2. Я попробовал отключить`loading="lazy"`. Не помогло. Надо еще тестить на реальных данных, короче. Хочешь сделаем какой-нибудь флаг в URL чтобы включать эту кнопку и потестим на продакшене? Я знаю как тяжело бывает воспроизвети на локалхосте.

Я ещё попробую накидать разных картинок локально, чтобы воспроизвести. Но если не получится, то флаг сильно помог бы. Если есть уже какая-то устоявшаяся практика применения url флагов, то ткни куда посмотреть – реализую аналогично.

> 3. При достижении конца в идеале бы менять иконку на стрелочку наверх. Сейчас прям сильно бросается в глаза :)

А у тебя в каком кейсе воспроизводится? Сейчас стрелочка должна меняться, либо если докликали до поля с вводом
 коммента (через кнопку или хоткеями), либо если доскроллили до конца страницы. Если я правильно предполагаю, то у тебя воспроизводится, когда ты доскроллил вручную до поля ввода коммента, но не доскроллил прям до конца страницы. Если так, то сделаю чтобы менялась на up немного раньше, когда доскроллили до поля с вводом коммента, например.

2021-10-03 19:04 UTC, vas3k commented
> Это именно та же проблема с изменением высоты страницы после подгрузки картинок? Или у тебя воспроизводится и на полностью подгруженных img?

Почти всегда воспроизводится. Вот например гайд по Омску: https://vas3k.club/guide/11648/ На нём даже если подгрузить все картинки и руками промотать страницу несколько раз туда-сюда, то первый клик отматывает куда-то сюда:

<img width="1388" alt="Screen 2021-10-03 at 21 01 28" src="https://user-images.githubusercontent.com/176344/135767752-0ecb9a6d-b5a7-40b1-866d-c25b38bb5b87.png">

Можешь взять исходник поста, создать его и проверить на локалхосте: https://vas3k.club/guide/11648.md


> Я ещё попробую накидать разных картинок локально, чтобы воспроизвести. Но если не получится, то флаг сильно помог бы. Если есть уже какая-то устоявшаяся практика применения url флагов, то ткни куда посмотреть – реализую аналогично.

Неа, нету. Сделай просто любой GET-параметр на JS, всё равно потом удалим как будем релизить. Можешь прямо в PR запихать, тогда этот замержим и будем в следующем уже фиксить что вылезло

> А у тебя в каком кейсе воспроизводится?

Так, отбой, теперь всегда работает :) Я поиграю еще, но на этот пункт пока забей да

2021-10-03 19:05 UTC, vas3k commented
С отматыванием кстати может быть та же проблема, что в оригинальном PR — автор пытался сделать чтобы фокусируемый элемент оказывался по центру экрана. Это звучит разумно, но в реальности только бесит. Давай отматывать как обычно — до верхней кромки окна браузера с небольшим отступом, как сейчас и работает любой #comment-bla

2021-10-03 19:10 UTC, vas3k commented
Блин, да, похоже это именно проблема отматывания до центра. Давай попробуем всегда отматывать до верхней границы окна с отступом типа 40-60px и протестим как будет не отключая lazy

2021-10-03 19:41 UTC, Zhurbin commented
> Блин, да, похоже это именно проблема отматывания до центра. Давай попробуем всегда отматывать до верхней границы окна с отступом типа 40-60px и протестим как будет не отключая lazy

Да, это оно. Закинул быстрофикс – поменял отмотку до границы окна с отступом (сделал 20px, выбрал чисто эмпирическим путём, т.к. там уже есть некоторый margin у блока коммента) вместо отмотки к центру экрана.  От скачков после загрузки картинок это не спасёт по идее, но мне так тоже больше нравится, более ожидаемое поведение стало.

А скачки после подгрузки картинок тогда ещё попробую воспроизвести локально (если не получится – сделаю url флаг).

2021-10-03 20:19 UTC, vas3k commented
> сделал 20px, выбрал чисто эмпирическим путём, т.к. там уже есть некоторый margin у блока коммента, но если что могу поменять на побольше

Стало лучше. Вообще можно сделать навигацию по #хешам, чтобы в URL подставлялся именно нужный хеш, а свойство `scroll-margin-top` (которое прописано у многих элементов) обрабатывалось как будто бы нативно. Ну это так, чисто если можно

Сейчас проверил — первый клик все равно отматывает к первому комменту, а должен отматывать именно к заголовку "120 комментариев". Иначе происходит путаница, как будто бы подсвечивается старый коммент.

2021-10-03 20:28 UTC, vas3k commented
Ну и полный pro-mode, у нас есть много таких комментариев, где новым является как родитель, так и его вложенные друзья:

<img width="880" alt="Screen 2021-10-03 at 22 25 00" src="https://user-images.githubusercontent.com/176344/135770375-b5cacb8d-622e-456c-b0b4-3b3c6d191b98.png">

Вот было бы совсем офигенно, если бы такой вложеный бутерброд пролистывался за один клик. Звучит нестандартно, но улучшает UX прям на порядок, я сейчас постоянно трачу кучу кликов чтобы пролистать реплаи к комменту, который мне заранее не интересен.

Вот было бы круто если бы кликер смотрел есть ли у следующего элемента родители с CSS классом `.comment-is-new` и пропускал их если есть. То есть абсолютно новый коммент первого или второго уровня пролистывался бы за один клик со всеми реплаями, не заставляя меня пробегать по каждому.

С таким UX уже можно идти на Оскар, так что это скорее как самая топовая хотелка :)

2021-10-03 21:08 UTC, vas3k commented
Либо я не знаю, изобрети какой-нибудь хитрый CSS селектор, мои скиллы тут чото всё :)

2021-10-03 21:40 UTC, Zhurbin commented
> Стало лучше. Вообще можно сделать навигацию по #хешам, чтобы в URL подставлялся именно нужный хеш, а свойство `scroll-margin-top` (которое прописано у многих элементов) обрабатывалось как будто бы нативно. Ну это так, чисто если можно

Вообще как вариант. Правда при этом потеряем анимацию при скролле, но можно жить и без неё. Но сейчас, при такой реализации, этот коммент (к которому скроллим) будет подсвечиваться зелёным, подумаю как это обойти, чтобы не поломать кейс прямого перехода по ссылке на новый комент. Или думаешь что наоборот лучше оставить чтобы он подсвечивался зелёным?

> Вот было бы совсем офигенно, если бы такой вложеный бутерброд пролистывался за один клик. Звучит нестандартно, но улучшает UX прям на порядок, я сейчас постоянно трачу кучу кликов чтобы пролистать реплаи к комменту, который мне заранее не интересен.

Угу, думаю не так уж проблемно будет сделать, попробую.

2021-10-03 21:43 UTC, vas3k commented
> Правда при этом потеряем анимацию при скролле

А вот не думаю. Погугли `scroll-behavior: smooth;`, оно новое, но вдруг поможет

> Или думаешь что наоборот лучше оставить чтобы он подсвечивался зелёным?

Думаю будет лучше оставить мигающими как сейчас, но если там больше 15 условных строк кода, то хер с ним, фигачь зелеными, проверим :)

2021-10-04 08:29 UTC, simnv commented
> Почти всегда воспроизводится. Вот например гайд по Омску: https://vas3k.club/guide/11648/ На нём даже если подгрузить все картинки и руками промотать страницу несколько раз туда-сюда, то первый клик отматывает куда-то сюда

Середина скролла выстраивается по верхней фиолетовой пунктирной линии, всё верно:
![image](https://user-images.githubusercontent.com/3754755/135802973-a032cf54-114b-4a73-b9ab-035d7dc5ac51.png)
Но от этого уже отказались, ладно.

Если хочется прыгать сначала к блоку комментариев, тогда уж лучше сделать 
`const fistComment = document.querySelector("#comments");`

> Вот бы кликер смотрел есть ли у следующего элемента родители с CSS классом .comment-is-new и пропускал их если есть.

Как-то так:
`document.querySelectorAll(".comment.comment-is-new, .comment:not(.comment-is-new) .reply.comment-is-new, .post-comments-list > .replies > .reply.comment-is-new, .post-comments-list > .replies > .reply:not(.comment-is-new) > .reply.comment-is-new")`

Было бы два варианта, для комментариев и реплаев в этих комментариях, но почему-то есть отдельные реплаи без топового комментария.

Ну и, похоже, надо учесть два уровня реплаев в этом случае. Получается уже волосато, и мб уже лучше проверять класс ближайшего родителя скриптом.

```js
document.querySelectorAll([
  ".comment.comment-is-new", // просто новые комментарии
  ".comment:not(.comment-is-new) > .comment-replies > .replies > .reply.comment-is-new", // новые реплаи к старым комментариям
  ".comment:not(.comment-is-new) > .comment-replies > .replies > .reply:not(.comment-is-new) > .reply-replies > .replies > .reply.comment-is-new", // новые реплаи на втором уровне к старым реплаям старых комментариев
  ".post-comments-list > .replies > .reply.comment-is-new", // новые реплаи без родительского комментария
  ".post-comments-list > .replies > .reply:not(.comment-is-new) > .reply.comment-is-new" // новые реплаи на втором уровне к старым реплаям без родительского комментария
].join());
```

Остаются скачки с картинками `loading=lazy`.

2021-10-04 09:13 UTC, vas3k commented
Давайте тогда отключать `loading=lazy` для картинок, что же поделать :(

Это в common/markdown/club_renderer.py

2021-10-04 10:52 UTC, simnv commented
> Давайте тогда отключать `loading=lazy` для картинок, что же поделать :(

Мб лучше рендерить img height? Для новых картинок всё равно обработчик PIL зовёт, можно и размеры подглядеть. Со старыми или миграцию сделать, или определять размеры перед отображением.

2021-10-04 10:53 UTC, vas3k commented
> Мб лучше рендерить img height? 

Маркдаун не поддерживает height вообще. Гитхаб из-за этого и перешел на HTML в комментах. Не хочется ломать всё нафиг, рили проще отключить

> Для новых картинок всё равно обработчик PIL зовёт

Картинки загружаются отдельным сервисом на Go у нас: github.com/vas3k/pepic

2021-10-04 12:29 UTC, simnv commented on frontend/static/js/components/CommentScrollArrow.vue
> +                const fistComment = document.querySelector(".comment");
А почему только к первому комментарию? Удобно же перемещаться кнопками по всем комментариям, даже когда все прочитаны.

2021-10-04 16:30 UTC, Zhurbin commented
> @Zhurbin Есть возможность мне дать права на коммит в https://github.com/zhurbin/vas3k.club? ![image](https://user-images.githubusercontent.com/3754755/135886276-212cd79d-3e94-4e6d-907b-b19cb1e233aa.png)
> 
> Переделал скроллинг на якоря (кроме scrollExtreme), поправил функцию onScroll - из-за косяков с округлением не всегда срабатывала, сделал пропуск реплаев непрочтённых комментариев, вернул перебор прочтённых комментариев когда нет непрочтённых.

Да, конечно, сейчас расшарю. Только сделай пуш лучше в отдельную ветку, ок? А то я уже поправил на якоря, огребём с мёрджем, лучше закинем через ПР в форке в ветку `feature/new-comments-scrolling` из твоей ветки.
А по-поводу перебора прочтённых комментариев когда нет непрочтённых – да, это я убрал т.к. показалось что в issue такое поведение было описано, но сейчас перечитал – вроде прямо это не написано, думаю можно вернуть.

Я тогда сейчас запушу свои измененения и расшарю тебе права. Правда ещё не всё доделал, осталось два момента:
- починить callback на окончание скролла после изменения document.location.hash (чтобы при доскролле был виден blink и убрался зелёный стиль подсветки target коммента)
- навешивать на html стиль scroll smooth только при скролле, иначе эффект срабатывает и при создании нового коммента, а это подбешивает (это частично завязано на предыдущий таск)

И, кстати, `loading=lazy` удалять не придётся – теперь всё работает ок и не прыгает даже при фоновой подгрузке картинок.

2021-10-04 16:44 UTC, vas3k commented
Изначально я не думал про прыжки по прочитанным, но если вам кажется так удобнее, давай сделаем. Только пусть тоже прыгает только по комментам первого уровня, реплаи нафиг, их палец устанет прокликивать

2021-10-04 16:50 UTC, simnv commented
> Да, конечно, сейчас расшарю. Только сделай пуш лучше в отдельную ветку, ок?

Отправил в новую ветку. Тупанул параллельно с созданием нового PR, прошу прощения :)

> * починить callback на окончание скролла после изменения document.location.hash (чтобы при доскролле был виден blink и убрался зелёный стиль подсветки target коммента)

Я делал проверкой локейшена, только через `Math.abs(el.offset - pageOffset) < 1` - там плавает от 0 до почти единицы разница, и с округлением не получится. Добавил ещё функцию getElementMargin, чтобы не хардкодить смещения.

> * навешивать на html стиль scroll smooth только при скролле, иначе эффект срабатывает и при создании нового коммента, а это подбешивает (это частично завязано на предыдущий таск)

Хорошая идея, да. Я оставил и :target и smooth-scroll, вроде не раздражало, но если убрать - то лучше убрать.

> И, кстати, `loading=lazy` удалять не придётся – теперь всё работает ок и не прыгает даже при фоновой подгрузке картинок.

Да, точно, в том же и была идея с якорями.

2021-10-04 16:54 UTC, simnv commented
> Изначально я не думал про прыжки по прочитанным, но если вам кажется так удобнее, давай сделаем. Только пусть тоже прыгает только по комментам первого уровня, реплаи нафиг, их палец устанет прокликивать

Так и делал, там просто `.comment`. Кстати, можно добавить кнопку на главную страницу и прыгать между `feed-post`.

2021-10-04 16:57 UTC, Zhurbin commented
> Кстати, можно добавить кнопку на главную страницу и прыгать между `feed-post`.

На главной кнопка будет конфликтовать с кнопкой открытия сайдбара на мобилке(( Так что думаю если и делать, то не в рамках этого таска.

2021-10-04 18:34 UTC, Zhurbin commented
@simnv Смёрджил твою ветку, спасибо за работу!

Правда поспешил я с заявлением, что не будет прыгать теперь. Не будет прыгать, но только если не добавлять анимацию скролла (`scroll-behavior: smooth;`). Пока что сделал без анимации.

@vas3k залил все изменения, бегло протестил – вроде теперь всё, кроме анимации скролла, работает как ожидается. Сегодня/завтра ещё тогда покопаю как можно будет вернуть анимацию и не терять при этом "не прыганье" при подгрузке контента.

2021-10-04 18:46 UTC, vas3k commented
@Zhurbin потестил. Две жалобы еще остались:

1. Похоже мы сломали зелёное выделение. Теперь если открыть ссылку с хешем, коммент быстренько подсветится зеленым и потухнет. Нужно починить обратно, это важная для UX фича
2. Без анимации все-таки грустненько. Не понимаешь куда тебя запульнула стрелочка, как будто случайно. Давай подумаем можно ли там хоть как-то анимировать. Я в принципе готов пожертвовать lazy loading'ом для этого

2021-10-04 18:49 UTC, Zhurbin commented
1. Ааа, понял, воспроизводится только в FF, поэтому сразу не словил (тестил в chrome/safari, там всё ок было). Посмотрю что там.
2. Согласен. Но на самом деле, сходу не уверен что отключение lazy loading'а спасёт, проверю.

2021-10-04 19:11 UTC, Zhurbin commented
> Похоже мы сломали зелёное выделение. Теперь если открыть ссылку с хешем, коммент быстренько подсветится зеленым и потухнет. Нужно починить обратно, это важная для UX фича

@vas3k  А можешь попробовать перезапустить firefox и страничку перезагрузить со сбросом кэша? Есть подозрение что это FF шакалит с селектором `:target`, у меня ща воспроизводилось в master ветке и даже в проде, а после релоада FF снова перестало.

2021-10-04 19:24 UTC, Zhurbin commented
@vas3k я так понимаю ты на прод данных можешь конкретную сборку проверить? Закинул тестовый коммит – убрал lazy loading и добавил анимацию. Локально вроде работает, но лучше глянуть на реальных данных.

2021-10-04 19:36 UTC, vas3k commented
> А можешь попробовать перезапустить firefox и страничку перезагрузить со сбросом кэша?

У меня стабильно повторяется. Скопировал URL, вставил в новое окошко — мельком увидел зеленый и всё. Но если прям там же кликнуть на дату или просто выделить адресную строку и нажать Enter — то зеленое выделение останется навсегда. То есть не работает только непосредственно при открытии страницы. В хроме проблемы нет, я проверил. Но FF нужен, у нас много его :(

> я так понимаю ты на прод данных можешь конкретную сборку проверить?

Тестирую на дампе базы у себя на локале, ага. Вот на путеводители из Омска в основном, там много картинок и комментов

Заметил вот еще что: скроллер не работает для незалогиненых пользователей. Если создать публичный пост, напостить туда комментов, а потом открыть его в же в "инкогнито" — то скролл отмотает до заголовка комментов, а дальше мотать не будет ни в какую.

2021-10-05 07:07 UTC, simnv requested changes
Вроде осталось уже немного

2021-10-05 07:07 UTC, simnv commented on frontend/static/js/components/CommentScrollArrow.vue
> +                if (Math.abs(offset - window.pageYOffset) < 1) {
Функция не срабатывает, когда экран достаточно высокий, и мы проматываем до элемента внизу. Предлагаю сделать так:
```js
                const scrolledToElement = Math.abs(offset - window.pageYOffset) < 1;
                const scrolledToBottom = Math.abs(document.body.getBoundingClientRect().height - window.pageYOffset - window.innerHeight) < 1;
                if (scrolledToElement || scrolledToBottom) {
```

2021-10-05 07:07 UTC, simnv commented on frontend/static/js/components/CommentScrollArrow.vue
> +                });
Резкий прыжок наверх, вместо плавного скролла. Укачивает. :)

Предлагаю так:
```js
                const topTarget = document.getElementById("app");
                this.scrollToElement(topTarget);
```

2021-10-05 07:07 UTC, simnv commented on frontend/static/js/components/CommentScrollArrow.vue
> +                comments = oldComments.length > 0 ? [...commentBlockArray, ...document.querySelectorAll(".comment")] : [];
Очень сложно. Достаточно одной строки:
```js
                // Новых нет, ищем начало блока комментариев и перебираем прочтённые комментарии
                comments = document.querySelectorAll("#comments, .comment");
```

2021-10-05 07:07 UTC, simnv commented on frontend/static/js/components/CommentScrollArrow.vue
> +            window.addEventListener('scroll', onScroll);
Поправь, пожалуйста, чтобы везде были одинаковые кавычки. Наверное, двойные

2021-10-05 08:13 UTC, simnv commented on frontend/static/js/components/CommentScrollArrow.vue
> +                const bottomOfWindow = scrollPosition + window.innerHeight === document.documentElement.offsetHeight;
Не срабатывает. Предлагаю так же:
```js
                const bottomOfWindow = Math.abs(document.body.getBoundingClientRect().height - window.pageYOffset - window.innerHeight) < 1;
```

2021-10-05 08:16 UTC, simnv commented on frontend/static/js/components/CommentScrollArrow.vue
> +                const topOfWindow = scrollPosition === 0;
scrollPosition тоже, наверное, не надо. Достаточно так:
```js
                const topOfWindow = window.pageYOffset === 0;
```

2021-10-05 08:53 UTC, Zhurbin commented
@simnv Спасибо за ревью, поправлю замечания!

> У меня стабильно повторяется. Скопировал URL, вставил в новое окошко — мельком увидел зеленый и всё. Но если прям там же кликнуть на дату или просто выделить адресную строку и нажать Enter — то зеленое выделение останется навсегда. То есть не работает только непосредственно при открытии страницы. В хроме проблемы нет, я проверил. Но FF нужен, у нас много его :(

@simnv @vas3k Ребят, а проверьте плиз воспроизводится ли этот баг в FF у вас в проде? У меня стабильно отрабатывает и в проде (ff, macos). Шаги воспроизведения:
- копируем ссылку с хешем коммента
- открываем новую вкладку в FF (важно открыть именно новую вкладку, либо заходить с вкладки, где не открыт vas3k.club)
- вставляем ссылку
- жмём enter

Пример в видео (тут FF к тому же даже не докрутил немного до нужного коммента):
https://user-images.githubusercontent.com/5123981/135990071-b608b555-14da-4183-b43d-236ea0810d12.mov

Кажется, FF как-то криво работает с :target селекторами. Лишний раз это подтверждает то, что если после воспроизведения бага ввести в консоль `document.querySelectorAll(':target')`, то получим пустой массив, хотя хеш в урле есть и компонент с таким id на странице присутствует. Бегло погуглил, 1:1 такую проблему не нашёл, самое близкое [вот](https://bugzilla.mozilla.org/show_bug.cgi?id=1220167). Ещё важный симптом - если уже находиться на vas3k.club, а потом вставить прямую ссылку на коммент, то всё будет ок.

Просто если этот баг воспроизводится и в проде, то лучше его вынести в отдельное issue, тут нужно глубже покопаться, может занять время.

2021-10-05 09:14 UTC, vas3k commented
@Zhurbin спулил последнюю версию, перебилдил через npm run watch, всё равно. Вот видео:

https://user-images.githubusercontent.com/176344/135995125-53602654-2249-41db-93e0-a3a1454eae35.mov

> Ещё важный симптом - если уже находиться на vas3k.club, а потом вставить прямую ссылку на коммент, то всё будет ок.

Да, всё так, там на видео видно в конце я просто нажал Enter в адресной строке

2021-10-05 09:18 UTC, vas3k commented
И я бы все-таки попытался как-то совместными силами поправить его именно в этом PR. Может еще фронтендеров в дев-чате привлёк к исследованию. На зеленом выделении у нас завязано много логики, если мы отломаем его — попортим UX куче юзеров

2021-10-05 09:19 UTC, Zhurbin commented
@vas3k не, с версией из этой ветки-то оно и понятно, а в master у тебя это воспроизводится тоже или нет?

2021-10-05 09:21 UTC, Zhurbin commented
Поправить можно и в этом PR, не вопрос. Я просто к тому, что судя по всему зелёное выделение отломалось не в этом PR, а уже было отломано.

2021-10-05 09:23 UTC, vas3k commented
@Zhurbin хммм, а ты прав, в мастере сейчас точно такая же фигня. Ох как плохо-то с этими браузерами :(

Ладно, тогда в этом PR не тратим время на баг, раз проблема старая. Соглашусь, что надо бы допилить новое, а потом искать баг. Поправь тогда как будет время комменты от @simnv и вот еще один мини-баг от меня:

- Если отмотать до комментария чтобы он «мигнул», а потом нажать на его дату — зеленое выделение вообще не появится (на других появляется). Похоже класс «митагия» перетирает все остальные классы

Остальное по UX вроде ок!

2021-10-05 10:00 UTC, simnv commented on frontend/static/js/components/CommentScrollArrow.vue
> +                if (Math.abs(offset - window.pageYOffset) < 1) {
if надо сделать чуть сложнее, иначе с самого низа наверх прыгаем рывком:
```js
if (scrolledToElement || (this.arrowDirection === "Down" && scrolledToBottom)) {
```

При этом в функции `scrollExtreme` надо передвинуть строки `this.arrowDirection = ` уже после this.scrollElement, иначе оно невовремя сработает.

2021-10-05 11:10 UTC, Zhurbin commented
Залил фиксы по ревью и фикс бага с кликом по дате в комменте.
Правда нашёл ещё один баг – при скролле проскакивают комменты с реплаями. Там судя по всему функция filteredComments отрабатывает не совсем как надо. Ближе к вечеру посмотрю что там происходит. @simnv пиши если вдруг найдешь как пофиксить.

![Watch the video](https://user-images.githubusercontent.com/5123981/136011533-8f0800bb-b521-4143-a788-08dd9089bf04.mov)

2021-10-05 13:18 UTC, simnv requested changes
@Zhurbin скролл, похоже, скачет, потому что в FF надо ctrl-shift-down давить. Если давим ctrl-down, то страница сначала скачет вниз, потом отрабатывает логика всех фильтров

2021-10-05 13:18 UTC, simnv commented on frontend/static/js/components/CommentScrollArrow.vue
> +                }
Чтобы FF не прыгал как попало, а срабатывал только по ctrl-shift-down/up, давай сделаем так:
```js
                // ctrl-up/down для всех, а в macos и FF - ⇧⌃↑/↓
                const isFirefox = ("netscape" in window) && / rv:/.test(navigator.userAgent);
                if (!e.ctrlKey || (isFirefox && !e.shiftKey)
                    || ["ArrowDown", "ArrowUp", "Down", "Up"].indexOf(e.key) < 0) {
                    return;
                }
```

2021-10-05 13:31 UTC, Zhurbin commented on frontend/static/js/components/CommentScrollArrow.vue
> +                comments = document.querySelectorAll("#comments, .comment");
А это выше уже обсуждалось – наоборот специально добавлял, чтобы после скролла было видно число комментов и фильтры.

2021-10-05 13:32 UTC, vas3k commented on frontend/static/js/components/CommentScrollArrow.vue
> +                comments = document.querySelectorAll("#comments, .comment");
Да, `#comments` именно что нужен, он визуально дает понять, что тебя перебросило к комментам, так что усложнение логики тут просто необходимо

2021-10-05 13:34 UTC, simnv commented on frontend/static/js/components/CommentScrollArrow.vue
> +                comments = document.querySelectorAll("#comments, .comment");
Тогда 
```js
comments = document.querySelectorAll(".post-comments-title, .comment");
```

2021-10-05 13:35 UTC, simnv commented on frontend/static/js/components/CommentScrollArrow.vue
> +                comments = document.querySelectorAll("#comments, .comment");
Иначе он берёт гигантский `#comments`, и сравнивает следующий шаг с его серединой. И получается что попало.

2021-10-05 13:36 UTC, Zhurbin commented on frontend/static/js/components/CommentScrollArrow.vue
> +            document.location.hash = '';
Да, точно. Именно в ff почему-то. Там, правда, если не обнулять, то может "залипнуть" хеш. В принципе, я потом добавил проверку `oldHash === newHash`, так что эта проблема уйдёт и из scrollExtreme это можно убрать.

2021-10-05 13:42 UTC, Zhurbin commented on frontend/static/js/components/CommentScrollArrow.vue
> +                }
Хммм, не, тут не только в FF дело. В Chrome тоже воспроизводится проскок комментов с реплаями (не всех), когда смотрел там именно в массиве filteredComments не было следующего коммента (который с реплаями), т.е. его в filter отсеивало, по-ходу из-за его высоты. Пока не было времени дальше подебажить.

Воспроизводилось на такой комбинации: коммент без реплая -> коммент без реплая -> коммент c 2 не вложенными реплаями ->коммент без реплая -> коммент без реплая (работает как на new так и на старых комментах).

2021-10-05 13:46 UTC, Zhurbin commented on frontend/static/js/components/CommentScrollArrow.vue
> +                comments = document.querySelectorAll("#comments, .comment");
хмм, а с `.post-comments-title` кста тоже проблема с высотой в filteredComments вылезает. Например, если открыть пост в инкогнито, то при таком селекторе он после этого вообще не будет скроллить к следующим комментам

2021-10-05 15:36 UTC, simnv requested changes
И ещё чуть-чуть... :)

2021-10-05 15:36 UTC, simnv commented on frontend/static/js/components/CommentScrollArrow.vue
> +             return parseInt(style.marginTop, 10);
Почему-то для `post-comments-title` нет `margin`, но есть `scroll-margin-top`. Нужно тогда использовать его:
```js
return parseInt(style.scrollMarginTop, 10);
```

2021-10-05 15:36 UTC, simnv commented on frontend/static/js/components/CommentScrollArrow.vue
> +            });
Переписываем, делаем проще:
```js
            const filteredComments = [...comments].filter((el) => {
                const elTop = el.getBoundingClientRect().top;
                const elTopMargin = this.getElementMargin(el);

                return (direction === "Down") ? elTop - elTopMargin > 1 : elTop < 0;
            });
```

2021-10-05 15:36 UTC, simnv commented on frontend/static/js/components/CommentScrollArrow.vue
> +        },
На элемент управления удобно кликать с шифтом, чтобы пойти в обратную сторону. Вроде вполне логично, давай попробуем:
```js
        onArrowClickHandler() {
            if (event.shiftKey) {
                const direction = this.arrowDirection == "Up" ? "Down" : "Up";
                this.scrollToComment(direction);
            } else if (this.arrowDirection == "Up") {
                this.scrollExtreme(this.arrowDirection);
            } else {
                this.scrollToComment(this.arrowDirection);
            }
        },
```

2021-10-05 15:36 UTC, simnv commented on frontend/static/js/components/CommentScrollArrow.vue
> +                }
Упростил `filteredComments`, мы же теперь не середину считаем

2021-10-05 15:38 UTC, simnv commented on frontend/static/js/components/CommentScrollArrow.vue
> +                }
Упростил `filteredComments`, теперь середину не считаем. Но кусок про Firefox всё же нужен

2021-10-05 15:46 UTC, simnv commented on common/markdown/club_renderer.py
> +        image_tag = f'<img src="{escape_html(src)}" alt="{escape_html(title)}">'
Давай теперь проверим `loading="lazy"`

2021-10-05 15:48 UTC, simnv commented on frontend/static/js/components/CommentScrollArrow.vue
> +                comments = document.querySelectorAll("#comments, .comment");
Проверил, с переделанными `filteredComments` и `getElementMargin` всё норм

2021-10-05 18:30 UTC, Zhurbin commented on common/markdown/club_renderer.py
> +        image_tag = f'<img src="{escape_html(src)}" alt="{escape_html(title)}">'
не, не работает(

2021-10-05 18:33 UTC, Zhurbin commented on frontend/static/js/components/CommentScrollArrow.vue
> +            });
А вот тут, кстати, чувствительности в 1 (в elTop - elTopMargin > 1) не хватит по-ходу. Опять FF шакалит при этом –по два раза один и тот же коммент проскакивает

2021-10-05 19:04 UTC, simnv approved these changes
Вроде всё норм. @vas3k, проверяй

2021-10-06 10:08 UTC, vas3k commented
Потестил на разных юзкейсах, вроде с ходу раздражающих вещей не нашел. Предлагаю мержить и собирать фидбек. Там явно вылезет какая-нибудь глупость на реальных данных, но её будем фиксить уже в последующих PRах.

От себя я лишь подумал, что я попробую сделать кнопку круглой, сейчас она как будто бы конфликтует с апвойтом визуально и выглядит как даунвоут :D 

@Zhurbin @simnv огромное спасибо вам, вы просто гении! Эту фичу год уже все хотят!

2021-10-06 10:08 UTC, vas3k approved these changes

2021-10-06 10:09 UTC, merged

2021-10-06 10:12 UTC, TiraelSedai commented
Выглядит отлично, @Zhurbin mad respect