Запоминать свернутость тредов
vas3k/vas3k.club pull request #752
Opened 2021-10-23 17:09 UTC by merelj

пр по ишью https://github.com/vas3k/vas3k.club/issues/729

мое первое знакомство со Vue, если есть идеи как это сделать более толково, с радостью поправлю 👍

2021-10-29 21:05 UTC, merelj commented
@vas3k готово 👍

2021-10-30 12:01 UTC, vas3k requested changes
Теперь импорты сломались :)

findParentForm и isCommunicationForm у тебя всё еще в utils же

```

WARNING in ./static/js/App.js 271:54-73
export 'isCommunicationForm' (imported as 'isCommunicationForm') was not found in './common/comments.js' (possible exports: getCollapsedCommentThreadsForTwoWeeks, getCollapsedCommentThreadsSet, handleCommentThreadCollapseToggle)
 @ ./static/js/main.js 5:0-27 33:8-20 36:8-19

webpack 5.30.0 compiled with 3 warnings in 4551 ms

```

2021-10-30 12:02 UTC, vas3k commented
+ ребейзни плиз ветку на мастер, там пакеты обновились, щас неудобно даунгрейдиться когда тестишь

2021-11-04 14:16 UTC, merelj commented
@vas3k поправил ✅ 
очень непривычно после Typescript'а, когда что-то в импортах ломается и не орет об этом сразу) поправил и отребейзился

2021-11-04 14:22 UTC, vas3k commented
Мой PyCharm заорал об этом сразу же :) Ок, протестирую на работоспособность как будет время еще раз

2021-11-07 21:59 UTC, vas3k approved these changes

2021-11-07 22:00 UTC, merged