Add more User fields to admin panel #872
vas3k/vas3k.club pull request #876
Opened 2022-01-18 19:14 UTC by dolshevsk

Как и обсуждалось в [issue](https://github.com/vas3k/vas3k.club/issues/872) добавил больше полей в админскую панель.

Выглядит это так:

<img width="407" alt="Screenshot 2022-01-18 at 8 13 18 PM" src="https://user-images.githubusercontent.com/36140450/150003255-46717faf-af9d-464a-9245-09a599f56c48.png">

Так же сделал небольшие дополнительные изменения по правилу бойскаута (комментарии оставлены ниже).

2022-01-18 19:18 UTC, dolshevsk commented on users/forms/admin.py
> +            ],
Решил не давать возможность назначать роль `god`

2022-01-18 19:28 UTC, dolshevsk commented on users/admin.py
> -
Долго изучал эту функция и показалось, что этот код unreachable, тк под нет логики в html и в админке ы форме такое поле не отсвечивает. 

Решил правилом бойскаута (хоть правило и спорное) убрать эту часть функционала.

2022-01-18 20:22 UTC, vas3k commented on users/forms/admin.py
> +            ],
Можно сделать ещё лучше: god может назначать какие угодно роли, moderator только curator, а curator не может ничего. Так будет иерархия

2022-01-18 20:22 UTC, vas3k commented on misc/views.py
> +    parliament = User.objects.filter(roles__contains=[User.ROLE_CURATOR])
Хз, так и так нормально

2022-01-18 20:23 UTC, vas3k commented on users/admin.py
> -
Похоже и правда нет, разбаны делаются установкой бана на 0 дней

2022-01-18 20:24 UTC, vas3k requested changes
Давай сделаем иерархию ролей, а в остальном все классно 👍

2022-01-19 08:35 UTC, vas3k commented on misc/views.py
> +    parliament = User.objects.filter(roles__contains=[User.ROLE_CURATOR])
А нет, я подумал, так нельзя и вот почему: в Парламенте могут быть не только Кураторы, но и модераторы и другие роли. А могут и не быть. Короче, по ачивке определять точнее

2022-01-19 16:49 UTC, dolshevsk commented on users/forms/admin.py
> +            ],
Сейчас начал делать и понял, что оперирую ролями напрямую, мы позволяем роли не только добавлять, но и убирать. Если начать учитывать возможные комбинации, добавления и удаления или замены одних ролей на другие, где плюс ко всему надо учитывать роли, которые были до этого, то получается целая задача коммивояжера.( например могут быть случаи [god, mod] -> [god], [mod, curator] -> [mod], [god] -> [mod, curator] и тд)

Предлагаю не превращать форму в алгоритм уровня фаанга, и сделал форму ролей отдельно ниже (как с шапками) и разрешить роли только добавлять причем по одном с соблюдения иерархии.

2022-01-19 16:55 UTC, vas3k commented on users/forms/admin.py
> +            ],
Ладно, тогда пофиг, давай сделаем как проще. Моя цель тут предотвратить саботажи, чтобы кто-то из кураторов не мог назначит себе роль god и пойти буянить :) Мне будет нормально если только god сможет менять роли, а остальные не смогут вообще

2022-01-19 16:59 UTC, dolshevsk commented on users/forms/admin.py
> +            ],
В целом, если хочется, чтобы роли могли другие так же и удалять, это сделать будет несложно, тут ключевой момент, что мы будем оперировать одной ролью за раз, а не по несколько.

2022-01-19 17:02 UTC, vas3k commented on users/forms/admin.py
> +            ],
Окей, а как с удалением будет? Надо же отображать список еще где-то? По мне так проще просто оставить эту фичу только для юзеров с ролью god, у них и так абсолютная власть

2022-01-19 17:15 UTC, dolshevsk commented on users/forms/admin.py
> +            ],
Вверху в форме можно показывать роли, которые есть у юзера. Вроде тут нет никаких проблем. Потом будет поле, где нужно выбрать роль, потом поле, где нужно выбрать действие (удалить или добавить) и все. 

На бэк будет приходить одна роль, и если `me` имеет право, чтобы оперировать этой ролью, тогда все ок.

2022-01-19 19:06 UTC, dolshevsk commented on users/forms/admin.py
> +            ],
<img width="868" alt="Screenshot 2022-01-19 at 8 06 47 PM" src="https://user-images.githubusercontent.com/36140450/150197541-05865ea3-c1eb-4465-836d-5f09e976b2fb.png">

2022-01-19 19:39 UTC, dolshevsk commented
Обновил PR. Добавил новую форму под роли и сделал поддержку иерархии. Так же ревертнул изменение по определению парламентария в /stats/.

2022-01-19 19:42 UTC, dolshevsk commented on users/models/user.py
> +    def get_roles_display(self):
Сделал по аналогии с тем, как это [делает django для сhoices](https://docs.djangoproject.com/en/4.0/ref/models/instances/#django.db.models.Model.get_FOO_display) (к сожалению, из коробки с `ArrayField` оно не работате)

2022-01-19 20:55 UTC, vas3k commented on users/forms/admin.py
> +            ],
Хех, ну ладно, давай так

2022-01-24 17:04 UTC, dolshevsk commented
@vas3k что решил по этому PR? Будем двигать его дальше?

2022-01-24 17:05 UTC, vas3k approved these changes
Будем!

2022-01-24 17:05 UTC, merged