fix: generate unique anchor (#942)
vas3k/vas3k.club pull request #943
Opened 2022-06-07 07:09 UTC by Diadlo

2022-06-07 19:01 UTC, dolshevsk commented on common/markdown/club_renderer.py
> +            while True:
А для какой цели тут нужен цикл? какой случай он обрабатывает? почему нельзя обойтись только строчкой `anchor = f"{slug}--{usage_counter}"`

2022-06-08 05:05 UTC, Diadlo commented on common/markdown/club_renderer.py
> +            while True:
Я не уверен, что slug не может оказаться `name--1`. Если 100% не может, то да, можно упростить

2022-06-08 05:10 UTC, Diadlo commented on common/markdown/club_renderer.py
> +            while True:
Посмотрел сейчас документацию slugify. Если честно, не вижу какого-то формального описания формата slug, но на практике вроде двойной `--` исключается. Могу упростить. Что скажете?

2022-06-08 05:40 UTC, Diadlo commented on common/markdown/club_renderer.py
> +            while True:
Переделал

2022-06-24 12:26 UTC, Diadlo commented
@dolshevsk на всякий случай напоминаю про PR

2022-06-24 12:37 UTC, dolshevsk commented
@Diadlo это тебе надо @vas3k тегать, только он может мерджить PR

2022-07-06 06:01 UTC, Diadlo commented
@vas3k Можешь посмотреть на PR? Вроде небольшая правка

2022-07-06 07:47 UTC, vas3k requested changes
Написал комментов

2022-07-06 07:47 UTC, vas3k commented on common/markdown/club_renderer.py
> +    def __get_anchor(self, slug):
Я не помню уже наизусть PEP-8, но что-то мне подсказывает, что двух подчеркиваний там нет. Я не использовал их года с 2012-го наверное.

2022-07-06 07:47 UTC, vas3k commented on common/markdown/club_renderer.py
> +        self.__used_anchor_slugs[slug] = usage_counter + 1
То же самое, два подчеркивания режут глаз

2022-07-06 07:47 UTC, vas3k commented on common/markdown/club_renderer.py
> +        if usage_counter == 0:
Почему бы не сделать просто `anchor = f"{slug}--{usage_counter or 0}"`? Мы и так ломаем все заголовки и забиваем болт на обратную совместимость, так зачем первый делать каким-то особенным?

2022-07-06 07:49 UTC, dmitvitalii commented on common/markdown/club_renderer.py
> +        if usage_counter == 0:
Тау у нас в постах есть навигации по контенту ручные, которые авторы аккуратненько делали ссылочками

2022-07-07 05:13 UTC, Diadlo commented on common/markdown/club_renderer.py
> +        if usage_counter == 0:
> Мы и так ломаем все заголовки и забиваем болт на обратную совместимость

Речь идет про этот PR? Тут совместимость не ломается. Собственно для этого и нужен отдельный случай. Я думаю кто-то мог сохранить себе ссылку на какой-то конкретный раздел, чтобы позже вернуться к ней (собственно что я пытался сделать, когда обнаружил данную проблему)

2022-07-07 05:13 UTC, Diadlo commented on common/markdown/club_renderer.py
> +    def __get_anchor(self, slug):
Done

2022-07-07 05:14 UTC, Diadlo commented on common/markdown/club_renderer.py
> +        self.__used_anchor_slugs[slug] = usage_counter + 1
Done

2022-07-11 11:14 UTC, Diadlo commented on common/markdown/club_renderer.py
> +        if usage_counter == 0:
@vas3k на всякий случай напоминаю

2022-07-17 08:03 UTC, Diadlo commented
@vas3k ping

2022-08-22 08:43 UTC, Diadlo commented
@vas3k ping

2022-09-01 11:48 UTC, Diadlo commented
@vas3k Есть еще замечания?

2022-10-24 12:04 UTC, Diadlo commented
@vas3k ping

2022-10-24 12:08 UTC, vas3k commented
@Diadlo спасиб за пинг. Я как обычно не уверен на счет введения глобального стейта, тем более нигде не очищаемого. У меня не было времени проверить это всё на утечки памяти и прочее, потому я пока не могу одобрить. Польза от этого изменения ничтожна, а потенциальные разрушения могут быть абсолютно внезапными.

2024-03-09 17:25 UTC, closed without merging