[WIP] vue-select for collectable tags
vas3k/vas3k.club pull request #950
Opened 2022-06-26 15:58 UTC by Holovin

2022-06-26 17:19 UTC, dolshevsk commented on search/api.py
> +        tags = tags.filter(name__icontains=prefix)
Если мы хотим матч по prefix, может будет лучше тогда использовать `istartswith` вместо `icontains`, чтобы не словить матч в середине тега или в конце?

2022-06-26 17:26 UTC, Holovin commented on search/api.py
> +        tags = tags.filter(name__icontains=prefix)
В таком случае полагаю оно будет искать с первого символа эмодзи, это можно обойти будет?

2022-06-26 17:56 UTC, dolshevsk commented on search/api.py
> +        tags = tags.filter(name__icontains=prefix)
а там перед prefix еще эмодзи идет? не, тогда `istartswith` не сработает. Тогда как есть норм 👍

2022-06-26 19:22 UTC, vas3k commented on search/api.py
> +        tags = tags.filter(name__icontains=prefix)
Да, так норм, давайте сделаем `icontains`

2022-06-26 19:23 UTC, vas3k commented
А можно еще приложить скриншотиков/видео как это все работает?

2022-06-28 00:47 UTC, Holovin commented
> А можно еще приложить скриншотиков/видео как это все работает?

Тут уже допиленная версия (на фоне той что залита):
https://user-images.githubusercontent.com/5501086/176063045-1f5a67ec-9014-4773-90ff-e07f62d7651e.mp4

Но пока есть ещё мелкие косяки (над которыми я сейчас работаю):
— прыгает поле ввода при клике
— стилей левых много, выпиливаю то что не используется + выношу цвета под переменные из theme.css

2022-06-28 14:50 UTC, vas3k requested changes

2022-06-28 14:50 UTC, vas3k commented on frontend/static/js/components/CollectionTag.vue
> +export default {
Мне не нравится название CollectionTag. Давай сделаем универсальный инпут типа InputAutosuggest, который принимал всё параметрами, включая эндпоинт для поиска = `/search/tags.json?prefix=${query}`, initialValue, multiple=true|false, regex, итд. Нам нужен будет такой инпут еще в куче других мест, его стоит сделать универсальным сразу

2022-06-28 20:20 UTC, Holovin commented on frontend/static/js/components/CollectionTag.vue
> +const EMOJI_REGEXP = /^(\u00a9|\u00ae|[\u2000-\u3300]|\ud83c[\ud000-\udfff]|\ud83d[\ud000-\udfff]|\ud83e[\ud000-\udfff]) .+$/;
А это хз, я взял из чата ту что сам Вастрик кидал при обсуждениях, возможно её и правда нужно поправить

2022-06-28 20:25 UTC, Holovin commented on frontend/static/js/components/CollectionTag.vue
> +                        isExist: true,
Оно нужно для валидации в ` <template #option="...` чтобы понимать что это «новый» option (который юзер только что добавит) или уже существующий (либа увы таких возможностей не даёт).

2022-06-28 20:31 UTC, Holovin commented on frontend/static/js/common/utils.js
> +export const debounce = (func, wait, immediate) => {
throttle срабатывает на первое события и фильтрует последующие в течение N сек
debounce пропускает все события и берёт последние как только они перестают идти в течение N сек

Для UX лучше чтобы поиск начинался после того как юзер перестанет быстро набирать текст. Например, если юзер начнёт набирать текст в поиск, то в случае в throttle поиск сработает после первого же символа (и сработает ещё пару раз в момент печати), а debounce только после окончания набора запроса. 

[(здесь есть примеры разницы между ними)](https://webdesign.tutsplus.com/tutorials/javascript-debounce-and-throttle--cms-36783)

2022-06-28 20:34 UTC, Holovin commented on frontend/static/js/components/CollectionTag.vue
> +export default {
Ок, вынесу отдельно с параметрами, но возможно потом придётся допиливать стили как-то если планируется использование не только в формах текущего стиля (как теги / список авторов)

2022-06-28 22:15 UTC, vas3k commented on frontend/static/js/components/CollectionTag.vue
> +const EMOJI_REGEXP = /^(\u00a9|\u00ae|[\u2000-\u3300]|\ud83c[\ud000-\udfff]|\ud83d[\ud000-\udfff]|\ud83e[\ud000-\udfff]) .+$/;
Ты можешь забить и не проверять регексп на фронте. Это требует особых усилий, которые пока напрасны, пусть это проверяется беком как щас

2022-06-28 22:16 UTC, vas3k commented on frontend/static/js/components/CollectionTag.vue
> +export default {
Стили я допилю, просто дай мне классы. А вот сам жс код универсальных компонентов я не смогу, так что очень надеюсь на тебя

2022-07-01 21:04 UTC, Holovin commented on frontend/static/js/components/CollectionTag.vue
> +export default {
Переделал компонент, сейчас должно быть универсально — всё что нужно прокидывается через пропсы. В коллекционных тегах работает, стили тоже ок. Возможно в будущем придётся что-то править, но пока выглядит норм вроде

2022-07-04 08:06 UTC, vas3k approved these changes
Проверил, вроде работает. По стилям тоже нравится, замержу пожалуй.

Было бы круто, если бы ты в следующем PR сделал еще и мульти-селект для соавторов. Там тоже есть такая же АПИха для поиска по префиксу: https://vas3k.club/search/users.json?prefix=vas

Только там нужен мульти-селект.

2022-07-04 08:11 UTC, merged