Представлять пользователя при входе в чат
vas3k/vas3k.club pull request #989
Opened 2022-10-12 13:04 UTC by orihomie

2022-10-13 07:34 UTC, igoose1 requested changes

2022-10-13 07:34 UTC, igoose1 commented on bot/handlers/whois.py
> +            f"🤨 К чату присоединился {whos_joined}, которого нет в Клубе. Гоните его, насмехайтесь над ним!",
Смущает, что тут может написаться "К чату присоединился 1234567...". Наверное, лучше брать имя профиля.

2022-10-13 07:34 UTC, igoose1 commented on bot/handlers/whois.py
> +@is_club_member
А точно нужен этот декоратор? Если он будет, то ниже "`if not user" никогда не сработает.

2022-10-13 10:09 UTC, kirillku approved these changes

2022-10-13 10:09 UTC, kirillku commented on bot/handlers/whois.py
> +            f"🤨 К чату присоединился {whos_joined}, которого нет в Клубе. Гоните его, насмехайтесь над ним!",
Может стоит делать как меншн?
```suggestion
            f"🤨 К чату присоединился @{whos_joined}, которого нет в Клубе. Гоните его, насмехайтесь над ним!",
```

2022-10-13 10:09 UTC, kirillku commented on bot/handlers/whois.py
> +    user = User.objects.filter(telegram_id=telegram_id).first()
я не уверен есть ли такое в питоне, но разве не должно быть так?
```suggestion
    user = User.objects.find(telegram_id=telegram_id)
```

2022-10-13 12:18 UTC, igoose1 commented on bot/handlers/whois.py
> +    user = User.objects.filter(telegram_id=telegram_id).first()
@kirillku, это Django ORM. Можно либо сделать `Column.objects.get(...)` и словить `Column.DoesNotExist` exception, либо `Column.objects.filter(...).first()` и получить `None`. Здесь выбран второй способ, он нормальный и часто используется.

2022-10-14 06:31 UTC, orihomie commented on bot/handlers/whois.py
> +@is_club_member
насчёт его необходимости не уверен, делал копипастой нижнего метода

2022-10-14 08:40 UTC, igoose1 commented on bot/handlers/whois.py
> +@is_club_member
Нижний нужен для того, чтобы неклубчанин не мог дернуть `/whois`.

2023-02-27 14:19 UTC, vas3k commented
Сделано через сторонние боты, закрываю

2023-02-27 14:19 UTC, closed without merging